import { Data, IProductInput } from "@/types";
import { toSlug } from "./utils";

const products: IProductInput[] = [
  {
    name: "womens mobile bag dress model ",
    slug: toSlug("womens mobile bag dress model"),
    category: "mobile-bag",
    images: ["/images/p11-1.jpg", "/images/p11-2.jpg", "/images/p11-3.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 20.0,
    listPrice: 0,
    brand: "crochet",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 5,
    countInStock: 2,
    description: "made with 100% handmade with crochet",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
  {
    name: "womens mobile bag with sling",
    slug: toSlug("womens mobile bag with sling"),
    category: "mobile-bag",
    images: ["/images/p12-1.jpg", "/images/p12-2.jpg", "/images/p12-3.jpg"],
    tags: ["todays-deal", "best-seller"],
    isPublished: true,
    price: 10.0,
    listPrice: 0,
    brand: "crochet",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 5,
    countInStock: 2,
    description: "made with 100% handmade with crochet",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
  {
    name: "womens mobile bag bottle holder",
    slug: toSlug("womens mobile bag bottle holder"),
    category: "mobile-bag",
    images: ["/images/p13-1.jpg", "/images/p13-2.jpg", "/images/p13-3.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 10.0,
    listPrice: 0,
    brand: "crochet",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 5,
    countInStock: 2,
    description: "made with 100% handmade with crochet",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
  {
    name: "womens side cross bag",
    slug: toSlug("womens side cross bag"),
    category: "side-bag",
    images: ["/images/p14-1.jpg", "/images/p14-2.jpg", "/images/p14-3.jpg"],
    tags: ["new-arrival", "todays-deal"],
    isPublished: true,
    price: 70.0,
    listPrice: 0,
    brand: "crochet",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 5,
    countInStock: 2,
    description: "made with 100% handmade with crochet",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
  {
    name: "womens side cross bag with zip inside",
    slug: toSlug("womens side cross bag with zip insde"),
    category: "side-bag",
    images: ["/images/p15-1.jpg", "/images/p15-2.jpg", "/images/p15-3.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 35.0,
    listPrice: 0,
    brand: "crochet",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 5,
    countInStock: 2,
    description: "made with 100% handmade with crochet",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
  {
    name: "womens mobile wallet with zip",
    slug: toSlug("womens mobile wallet with zip"),
    category: "mobile-wallet",
    images: ["/images/p16-1.jpg", "/images/p16-2.jpg", "/images/p16-3.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 15.0,
    listPrice: 0,
    brand: "crochet",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 5,
    countInStock: 2,
    description: "made with 100% handmade with crochet",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
  {
    name: "womens mobile wallet with flower model",
    slug: toSlug("womens mobile wallet with flower model"),
    category: "mobile-wallet",
    images: ["/images/p17-1.jpg", "/images/p17-2.jpg", "/images/p17-3.jpg"],
    tags: ["best-seller", "featured"],
    isPublished: true,
    price: 30.0,
    listPrice: 0,
    brand: "crochet",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 5,
    countInStock: 2,
    description: "made with 100% handmade with crochet",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
  {
    name: "womens mobile shell wallet",
    slug: toSlug("womens mobile shell wallet"),
    category: "mobile-wallet",
    images: ["/images/p18-1.jpg", "/images/p18-2.jpg", "/images/p18-3.jpg"],
    tags: ["new-arrival", "todays-deal"],
    isPublished: true,
    price: 15.0,
    listPrice: 0,
    brand: "crochet",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 5,
    countInStock: 2,
    description: "made with 100% handmade with crochet",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
  {
    name: "womens hair band",
    slug: toSlug("womens hair band"),
    category: "hair-band",
    images: ["/images/p19-1.jpg", "/images/p19-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 6.0,
    listPrice: 0,
    brand: "crochet",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 5,
    countInStock: 2,
    description: "made with 100% handmade with crochet",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
  {
    name: "Kids dress",
    slug: toSlug("kids dress"),
    category: "kids-dress",
    images: ["/images/p20-1.jpg", "/images/p20-2.jpg", "/images/p20-3.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 20.0,
    listPrice: 0,
    brand: "crochet",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 5,
    countInStock: 2,
    description: "made with 100% handmade with crochet",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
];

const data: Data = {
  products,
  headerMenus: [
    {
      name: "Today's deal",
      href: "/search?tag=todays-deal",
    },
    {
      name: "New Arrivals",
      href: "/search?tag=new-arrivals",
    },
    {
      name: "Featured Products",
      href: "/search?tag=featured",
    },
    {
      name: "Best Sellers",
      href: "/search?tag=best-seller",
    },
    {
      name: "Browsing History",
      href: "/#browsing-history",
    },
    {
      name: "Customer Service",
      href: "/page/customer-service",
    },
    {
      name: "About Us",
      href: "/page/about-us",
    },
    {
      name: "Help",
      href: "/page/help",
    },
  ],

  carousels: [
    {
      title: "Most popular side bag for sale",
      buttonCaption: "shop now",
      image: "/images/banner1.png",
      url: "/search?category=mobile-bag",
      isPublished: true,
    },
    {
      title: "Most likely Hair band for sale",
      buttonCaption: "shop now",
      image: "/images/banner3.png",
      url: "/search?category=hair-band",
      isPublished: true,
    },
    {
      title: "Most popular wallet pouch for sale",
      buttonCaption: "shop now",
      image: "/images/banner2.png",
      url: "/search?category=wallet-bag",
      isPublished: true,
    },
  ],
};

export default data;
